import React, { useState } from 'react';
import styles from './ContextualInsightModal.module.css';

const ContextualInsightModal = ({ 
  isOpen, 
  onClose, 
  insightData, 
  aiText, 
  aiLoading, 
  selectedMode,
  onModeChange 
}) => {
  const [copiedText, setCopiedText] = useState('');

  // Enhanced text formatting for professional display
  const formatAIResponse = (text) => {
    if (!text) return '';
    
    return text
      // Format headers
      .replace(/^(EXECUTIVE SUMMARY|STRATEGIC IMPLICATIONS|OPPORTUNITIES & RISKS|RECOMMENDED ACTIONS|SUCCESS METRICS|TREND ANALYSIS|PREDICTIVE INDICATORS|SCENARIO PLANNING|EARLY WARNING SIGNALS|CONFIDENCE INTERVALS|KEY INSIGHT|IMMEDIATE ACTIONS|BUSINESS IMPACT|WHAT THIS MEANS|WHY IT MATTERS|SIMPLE COMPARISON|WHAT TO DO NEXT|KEY TAKEAWAY):/gm, '**$1:**')
      // Format bullet points
      .replace(/^[•·-]\s/gm, '• ')
      // Format numbered lists
      .replace(/^(\d+)\.\s/gm, '$1. ')
      // Emphasize key terms
      .replace(/\b(HIGH|MEDIUM|LOW|CRITICAL|URGENT|IMMEDIATE)\b/g, '**$1**')
      // Format percentages and numbers
      .replace(/(\d+(?:\.\d+)?%)/g, '**$1**')
      .replace(/(\$[\d,]+(?:\.\d{2})?)/g, '**$1**');
  };

  // Simple markdown-like renderer for professional formatting
  const renderFormattedText = (text) => {
    if (!text) return null;
    
    const formattedText = formatAIResponse(text);
    const lines = formattedText.split('\n');
    
    // Special styling for "explain" mode
    const isExplainMode = selectedMode === 'explain';
    
    return lines.map((line, index) => {
      // Headers
      if (line.match(/^\*\*(.*?):\*\*$/)) {
        const headerText = line.replace(/^\*\*(.*?):\*\*$/, '$1');
        return (
          <h3 key={index} style={{ 
            color: isExplainMode ? '#22c55e' : '#fbbf24', 
            fontWeight: '700', 
            margin: '1.5rem 0 0.75rem 0',
            fontSize: isExplainMode ? '1.1rem' : '1rem',
            borderBottom: `1px solid ${isExplainMode ? 'rgba(34, 197, 94, 0.2)' : 'rgba(251, 191, 36, 0.2)'}`,
            paddingBottom: '0.25rem'
          }}>
            {headerText}:
          </h3>
        );
      }
      
      // Bullet points
      if (line.startsWith('• ')) {
        const processedLine = line.substring(2).replace(/\*\*(.*?)\*\*/g, `<strong style="color: ${isExplainMode ? '#22c55e' : '#fbbf24'}; font-weight: 700;">$1</strong>`);
        return (
          <div key={index} style={{ 
            margin: '0.5rem 0', 
            paddingLeft: '1rem',
            color: '#cbd5e1',
            display: 'flex',
            alignItems: 'flex-start'
          }}>
            <span style={{ color: isExplainMode ? '#22c55e' : '#fbbf24', marginRight: '0.5rem', marginTop: '0.1rem' }}>•</span>
            <span dangerouslySetInnerHTML={{ __html: processedLine }} />
          </div>
        );
      }
      
      // Regular text with bold formatting
      if (line.trim()) {
        const processedLine = line.replace(/\*\*(.*?)\*\*/g, `<strong style="color: ${isExplainMode ? '#22c55e' : '#fbbf24'}; font-weight: 700;">$1</strong>`);
        return (
          <p key={index} style={{ 
            margin: '0.75rem 0', 
            color: '#e2e8f0',
            lineHeight: '1.6'
          }} dangerouslySetInnerHTML={{ __html: processedLine }} />
        );
      }
      
      // Empty lines for spacing
      return <br key={index} />;
    });
  };

  if (!isOpen || !insightData) return null;

  const copyToClipboard = async (text, label) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedText(label);
      setTimeout(() => setCopiedText(''), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const formatForChatbot = (text) => {
    // Enterprise-grade formatting for chatbot integration
    const timestamp = new Date().toLocaleString();
    const analysisMode = selectedMode.charAt(0).toUpperCase() + selectedMode.slice(1);
    
    // Special formatting for "explain" mode - more conversational
    if (selectedMode === 'explain') {
      return `💬 **BUSINESS DATA EXPLANATION**

**What we're looking at:** ${insightData.title}
**Explanation Type:** Business Explainer Summary
**Generated:** ${timestamp}

---

${text}

---

**Note:** This explanation is designed to be easy to understand for anyone, regardless of their technical or business background.

*Generated by AI Business Intelligence Agent*`;
    }
    
    return `📊 **BUSINESS INTELLIGENCE BRIEF**

**Analysis Subject:** ${insightData.title}
**Analysis Type:** ${analysisMode} Analysis
**Generated:** ${timestamp}
**Data Source:** Transaction Patterns Dashboard

---

${text}

---

**Confidence Level:** High (Based on verified transaction data)
**Next Review:** Recommended within 24-48 hours
**Distribution:** Approved for C-level and strategic planning discussions

*This analysis was generated using enterprise-grade AI business intelligence tools*`;
  };

  const formatForReport = (text) => {
    // Professional report format
    const timestamp = new Date().toLocaleString();
    const analysisMode = selectedMode.charAt(0).toUpperCase() + selectedMode.slice(1);
    
    // Special formatting for "explain" mode - more accessible
    if (selectedMode === 'explain') {
      return `BUSINESS DATA EXPLANATION REPORT
${'-'.repeat(50)}

SUMMARY
Subject: ${insightData.title}
Report Type: Business Explainer Report
Generated: ${timestamp}
Prepared by: AI Business Intelligence Agent

EXPLANATION
${'-'.repeat(15)}

${text}

REPORT NOTES
${'-'.repeat(15)}
• This report uses simple language for broad accessibility
• Technical jargon has been avoided or explained
• Suitable for all stakeholders regardless of technical background
• Data Source: Transaction Patterns Dashboard
• Classification: General Distribution

END OF REPORT`;
    }
    
    return `BUSINESS INTELLIGENCE REPORT
${'-'.repeat(50)}

EXECUTIVE SUMMARY
Subject: ${insightData.title}
Analysis Type: ${analysisMode}
Generated: ${timestamp}
Analyst: AI Business Intelligence System

DETAILED ANALYSIS
${'-'.repeat(20)}

${text}

REPORT METADATA
${'-'.repeat(15)}
• Data Source: Transaction Patterns Dashboard
• Analysis Confidence: High
• Methodology: Advanced AI Analytics
• Review Cycle: 24-48 hours
• Classification: Internal Use

END OF REPORT`;
  };

  const modes = [
    { 
      key: 'quick', 
      label: 'Executive Brief', 
      icon: '⚡', 
      description: 'Rapid decision-making insights',
      subtitle: 'C-level summary format',
      tooltip: 'Concise executive summary under 150 words.&#10;Perfect for quick decision-making and rapid briefings.'
    },
    { 
      key: 'strategic', 
      label: 'Strategic Analysis', 
      icon: '🎯', 
      description: 'Comprehensive business intelligence',
      subtitle: 'Board presentation ready',
      tooltip: 'Comprehensive strategic analysis with implications and recommendations.&#10;Ideal for board presentations and strategic planning sessions.'
    },
    { 
      key: 'forecast', 
      label: 'Predictive Intelligence', 
      icon: '📈', 
      description: 'Forward-looking trend analysis',
      subtitle: 'Risk & opportunity assessment',
      tooltip: 'Predictive analysis with trend forecasting and scenario planning.&#10;Helps with resource allocation and risk management decisions.'
    },
    { 
      key: 'explain', 
      label: 'Business Explainer', 
      icon: '💬', 
      description: 'Simple explanation for everyone',
      subtitle: 'No jargon, easy to understand',
      tooltip: 'Plain language explanation accessible to all stakeholders.&#10;Perfect for non-technical team members and general communication.'
    }
  ];

  return (
    <div className={styles.modalOverlay} onClick={onClose}>
      <div className={styles.modalContent} onClick={e => e.stopPropagation()}>
        <div className={styles.modalHeader}>
          <div className={styles.headerContent}>
            <div className={styles.shiftClickIndicator}>
              <span className={styles.shiftIcon}>⇧</span>
              <span className={styles.clickIcon}>🖱️</span>
            </div>
            <div>
              <h2 className={styles.modalTitle}>Business Intelligence Analysis</h2>
              <p className={styles.modalSubtitle}>Enterprise-grade AI insights</p>
            </div>
          </div>
          <button 
            className={styles.closeButton} 
            onClick={onClose}
            title="Close Business Intelligence Analysis"
          >
            ×
          </button>
        </div>

        <div className={styles.dataContext}>
          <h3 className={styles.contextTitle}>{insightData.title}</h3>
          {insightData.subtitle && (
            <p className={styles.contextSubtitle}>{insightData.subtitle}</p>
          )}
          
          {insightData.metrics && insightData.metrics.length > 0 && (
            <div className={styles.metricsGrid}>
              {insightData.metrics.map((metric, index) => (
                <div key={index} className={styles.metricCard}>
                  <span className={styles.metricLabel}>{metric.label}</span>
                  <span className={styles.metricValue}>{metric.value}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className={styles.modeSelector}>
          <h4 className={styles.sectionTitle}>Analysis Mode</h4>
          <div className={styles.modeButtons}>
            {modes.map(mode => (
              <button
                key={mode.key}
                className={`${styles.modeButton} ${selectedMode === mode.key ? styles.active : ''}`}
                onClick={() => onModeChange(mode.key)}
                disabled={aiLoading}
                data-mode={mode.key}
                title={mode.tooltip}
              >
                <span className={styles.modeIcon}>{mode.icon}</span>
                <div className={styles.modeText}>
                  <span className={styles.modeLabel}>{mode.label}</span>
                  <span className={styles.modeDescription}>{mode.description}</span>
                  <span className={styles.modeSubtitle}>{mode.subtitle}</span>
                </div>
              </button>
            ))}
          </div>
        </div>

        <div className={styles.aiResponse}>
          <h4 className={styles.sectionTitle}>AI Analysis</h4>
          <div className={styles.responseContainer}>
            {aiLoading ? (
              <div className={styles.loadingContainer}>
                <div className={styles.loadingSpinner}></div>
                <p>
                  {selectedMode === 'explain' 
                    ? 'Creating business explanation...' 
                    : `Generating ${selectedMode} insights...`
                  }
                </p>
              </div>
            ) : aiText ? (
              <div className={styles.responseText}>
                <div className={styles.aiTextContent}>
                  {renderFormattedText(aiText)}
                </div>
                <div className={styles.actionButtons}>
                  <button 
                    className={`${styles.copyButton} ${styles.primary}`}
                    onClick={() => copyToClipboard(formatForChatbot(aiText), 'Chatbot')}
                    title="Copy formatted text optimized for chatbot conversations.&#10;Includes metadata and professional formatting."
                  >
                    {copiedText === 'Chatbot' ? '✅ Copied!' : '🤖 Copy for Chatbot'}
                  </button>
                  <button 
                    className={styles.copyButton}
                    onClick={() => copyToClipboard(formatForReport(aiText), 'Report')}
                    title="Copy as a formal business report with headers and metadata.&#10;Perfect for documentation and presentations."
                  >
                    {copiedText === 'Report' ? '✅ Copied!' : '📄 Copy as Report'}
                  </button>
                  <button 
                    className={styles.copyButton}
                    onClick={() => copyToClipboard(aiText, 'Raw')}
                    title="Copy the raw AI analysis text without formatting.&#10;Use for custom formatting or integration."
                  >
                    {copiedText === 'Raw' ? '✅ Copied!' : '📋 Copy Raw Text'}
                  </button>
                </div>
              </div>
            ) : (
              <div className={styles.noResponse}>
                <p>Select a mode above to generate insights</p>
              </div>
            )}
          </div>
        </div>

        <div className={styles.modalFooter}>
          <div className={styles.footerInfo}>
            <div className={styles.metadataGrid}>
              <div className={styles.metadataItem}>
                <span className={styles.metadataLabel}>Generated:</span>
                <span className={styles.metadataValue}>
                  {new Date(insightData.timestamp).toLocaleString()}
                </span>
              </div>
              <div className={styles.metadataItem}>
                <span className={styles.metadataLabel}>Analysis Type:</span>
                <span className={styles.metadataValue}>
                  {selectedMode.charAt(0).toUpperCase() + selectedMode.slice(1)}
                </span>
              </div>
              <div className={styles.metadataItem}>
                <span className={styles.metadataLabel}>Confidence:</span>
                <span className={styles.metadataValue}>High</span>
              </div>
              <div className={styles.metadataItem}>
                <span className={styles.metadataLabel}>Classification:</span>
                <span className={styles.metadataValue}>Internal Use</span>
              </div>
            </div>
          </div>
          <button 
            className={styles.closeFooterButton} 
            onClick={onClose}
            title="Close this analysis and return to dashboard"
          >
            Close Analysis
          </button>
        </div>
      </div>
    </div>
  );
};

export default ContextualInsightModal;